version: '3.13'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 987654
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:987654@db/testdb
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge